# Generated by Django 2.1.15 on 2021-05-23 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('OtherNames', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=255)),
                ('Affiliation', models.CharField(max_length=255)),
                ('BioData', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Board Members',
            },
        ),
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Source', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Link', models.CharField(max_length=255)),
                ('Slug', models.SlugField()),
                ('Date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Calls',
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommitteeName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('OtherNames', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=255)),
                ('Affiliation', models.CharField(max_length=255)),
                ('BioData', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Committee Members',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('Name', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Date', models.CharField(max_length=35)),
                ('Slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=255)),
                ('Message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('FileSize', models.CharField(max_length=55)),
                ('FileFormat', models.CharField(max_length=55)),
                ('File', models.FileField(upload_to='')),
                ('Slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('MemberID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('OtherNames', models.CharField(blank=True, max_length=50, null=True)),
                ('Designation', models.CharField(max_length=255)),
                ('Affiliation', models.CharField(max_length=255)),
                ('PaymentStatus', models.BooleanField(default=False)),
                ('BioData', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MembershipCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Membership Categories',
            },
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Membership Types',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('Name', models.CharField(max_length=55)),
                ('Description', models.TextField()),
                ('DatePublished', models.DateTimeField(auto_now_add=True)),
                ('Slug', models.SlugField()),
                ('File', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo', models.ImageField(upload_to='')),
                ('Name', models.CharField(max_length=255)),
                ('Profile', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PartnerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Partner Categories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Slug', models.SlugField()),
                ('Status', models.BooleanField(default=False)),
                ('Implementers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Slug', models.SlugField()),
                ('DatePublished', models.DateTimeField(auto_now_add=True)),
                ('Authors', models.CharField(max_length=655)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Provider', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Link', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Secretariat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('OtherNames', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=255)),
                ('BioData', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=255)),
                ('Testimony', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TitleName', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Titles',
            },
        ),
        migrations.AddField(
            model_name='testimonial',
            name='Title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Titles'),
        ),
        migrations.AddField(
            model_name='secretariat',
            name='Title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Titles'),
        ),
        migrations.AddField(
            model_name='partner',
            name='CategoryName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.PartnerCategory'),
        ),
        migrations.AddField(
            model_name='member',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.MembershipCategory'),
        ),
        migrations.AddField(
            model_name='member',
            name='Membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.MembershipType'),
        ),
        migrations.AddField(
            model_name='committeemembership',
            name='Title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Titles'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='Title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Titles'),
        ),
    ]
