# Generated by Django 2.1.15 on 2021-05-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='DatePublished',
            field=models.DateTimeField(),
        ),
    ]
