# Generated by Django 2.1.15 on 2021-05-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_auto_20210525_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='DatePublished',
            field=models.DateField(),
        ),
    ]
